### PR TITLE
With richard's help, added manifest file and fixes to pypi package. T…

### LINKED ISSUE #22: Fix Pypi Issues
Pypi is acting funky in regards to package detection. Fix this

### PR DESCRIPTION
**Pull request by cuff-links**
Closes #22

### CODE REVIEW

**Comment by cuff-links** [comment]
@rpappalax @pdehaan Check it out, homies. Hopefully, this is good enough.Integrating it with services test and it seems to be working just fine.

**Comment by rpappalax** [comment]
@silne30 nice!  does it pip install for you now?

**Comment by cuff-links** [comment]
Yep

**Comment by cuff-links** [comment]
@Rpapallax yes it does.

**Pull request merged**
